name: Node.js build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_user_auth:
    defaults:
      run:
        working-directory: user-auth/graphtutorial

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x, 24.x ]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Copy settings file
      run: |
        cp appSettings.example.js appSettings.js
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint

  build_app_auth:
    defaults:
      run:
        working-directory: app-auth/graphapponlytutorial

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x, 24.x ]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Copy settings file
      run: |
        cp appSettings.example.js appSettings.js
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint
